# -*- coding: utf-8 -*-
"""IS IT PRIME NUMBER?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRCEhunTp2lcsfLDdXrXC45KM4cAYdHM
"""

number = int(input("Please enter a number: "))
counter = 0
for i in range(2, number):
    
        if number % i == 0:
            counter += 1
            
if number == 0 or number == 1 or counter > 0 :
    print(f"{number} is NOT a prime number!")
else :  # elif counter == 0 :
    print(f"{number} is a prime number!")